# courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.course_list, name='list'),
    path('my-courses/', views.enrolled_courses, name='enrolled_courses'),
    path('certificates/', views.certificate_list, name='certificate_list'),
    path('<str:course_slug>/', views.course_detail, name='detail'),
    path('<str:course_slug>/module/<int:module_id>/', views.module_detail, name='module_detail'),
    path('<str:course_slug>/module/<int:module_id>/quizzes/', views.quiz_list, name='quiz_list'),
    path('quiz/<int:quiz_id>/take/', views.take_quiz, name='take_quiz'),
    path('quiz/result/<int:attempt_id>/', views.quiz_result, name='quiz_result'),
    path('<str:course_slug>/initiate-payment/', views.initiate_payment, name='initiate_payment'),
    path('verify-payment/<str:reference>/', views.verify_payment, name='verify_payment'),
    path('certificate/public/<uuid:uuid>/', views.public_certificate_view, name='public_certificate'),
    path('certificate/<uuid:uuid>/pdf/', views.download_certificate_pdf, name='download_certificate_pdf'),
    # Add these to your existing courses/urls.py
    path('digievolveadmin/courses/', views.admin_course_list, name='admin_course_list'),
    path('digievolveadmin/courses/add/', views.admin_add_course, name='admin_add_course'),
    path('digievolveadmin/courses/<int:course_id>/edit/', views.admin_course_edit, name='admin_course_edit'),
    path('digievolveadmin/courses/<int:course_id>/modules/', views.admin_course_modules, name='admin_course_modules'),
    path('digievolveadmin/courses/<int:course_id>/delete/', views.admin_course_delete, name='admin_course_delete'),
    path('digievolveadmin/modules/', views.admin_modules, name='admin_modules'),
    path('digievolveadmin/quizzes/', views.admin_quizzes, name='admin_quizzes'),
    path('digievolveadmin/courses/<int:course_id>/modules/add/', views.admin_add_module, name='admin_add_module'),
    path('digievolveadmin/courses/<int:course_id>/modules/<int:module_id>/edit/', views.admin_edit_module, name='admin_edit_module'),
    path('digievolveadmin/courses/<int:course_id>/modules/<int:module_id>/delete/', views.admin_delete_module, name='admin_delete_module'),
    path('courses/<int:course_id>/modules/<int:module_id>/quiz/',  views.admin_module_quiz, name='admin_module_quiz'),
    
    path('courses/<int:course_id>/modules/reorder/',
          views.admin_reorder_modules,
          name='admin_reorder_modules'),



     path('courses/<int:course_id>/modules/<int:module_id>/quiz/add-question/',
          views.admin_add_question,
          name='admin_add_question'),
     path('courses/<int:course_id>/modules/<int:module_id>/quiz/edit-question/',
          views.admin_edit_question,
          name='admin_edit_question'),
     path('courses/<int:course_id>/modules/<int:module_id>/quiz/delete-question/<int:question_id>/',
          views.admin_delete_question,
          name='admin_delete_question'),
     path('courses/<int:course_id>/modules/<int:module_id>/quiz/get-question/',
          views.admin_get_question,
          name='admin_get_question'),
     path('courses/<int:course_id>/modules/<int:module_id>/quiz/settings/',
          views.admin_update_quiz_settings,
          name='admin_update_quiz_settings'),

     path('quiz/<int:quiz_id>/settings/',
          views.admin_update_quiz_settings,
          name='admin_update_quiz_settings'),
     path('quiz/<int:quiz_id>/questions/add/',
          views.admin_add_question,
          name='admin_add_question'),
     path('quiz/<int:quiz_id>/questions/<int:question_id>/edit/',
          views.admin_edit_question,
          name='admin_edit_question'),
     path('quiz/<int:quiz_id>/questions/<int:question_id>/delete/',
          views.admin_delete_question,
          name='admin_delete_question'),
     path('questions/get/',
          views.admin_get_question,
          name='admin_get_question'),


     path('quiz/<int:quiz_id>/settings/',
         views.admin_quiz_settings,
         name='admin_quiz_settings'),
     path('quiz/<int:quiz_id>/questions/',
         views.admin_quiz_questions,
         name='admin_quiz_questions'),
     path('quiz/<int:quiz_id>/edit/',
         views.admin_edit_quiz,
         name='admin_edit_quiz'),
     path('quiz/<int:quiz_id>/delete/',
         views.admin_delete_quiz,
         name='admin_delete_quiz'),
     path('quiz/<int:quiz_id>/results/',
         views.admin_quiz_results,
         name='admin_quiz_results'),
     path('quiz/<int:quiz_id>/attempts/<int:attempt_id>/',
          views.admin_quiz_attempt_detail,
          name='admin_quiz_attempt_detail'),


     # courses/urls.py
# Quiz Management URLs
path('quiz/<int:quiz_id>/edit/',
     views.admin_edit_quiz,
     name='admin_edit_quiz'),
path('quiz/<int:quiz_id>/delete/',
     views.admin_delete_quiz,
     name='admin_delete_quiz'),
path('quiz/<int:quiz_id>/questions/add/',
     views.admin_add_question,
     name='admin_add_question'),
path('quiz/<int:quiz_id>/questions/<int:question_id>/edit/',
     views.admin_edit_question,
     name='admin_edit_quiz_question'),
path('quiz/<int:quiz_id>/questions/<int:question_id>/delete/',
     views.admin_delete_question,
     name='admin_delete_question'),
path('quiz/questions/get/',
     views.admin_get_question,
     name='admin_get_quiz_question'),
]